Extension { #name : 'DelegatorUtilityRudesheim' }

{ #category : '*Rudesheim-Utility' }
DelegatorUtilityRudesheim class >> Basic [
	^ BasicDelegatorUtilityRudesheim.
]

{ #category : '*Rudesheim-Utility' }
DelegatorUtilityRudesheim class >> ForAccessing [
	^ ForAccessingDelegatorUtilityRudesheim.
]

{ #category : '*Rudesheim-Utility' }
DelegatorUtilityRudesheim class >> ForProcessingMessage [
	^ MessageForwardingDelegatorUtilityRudesheim.
]
